import React from "react";
import Head from "next/head";

const Login = () => {
  return (
    <div>
      <Head>
        <title>Journal App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Login</main>
    </div>
  );
};

export default Login;
